<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.oakpay</groupId>
    <artifactId>oakpay</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>OakPay</name>
    <description>OakPay digital asset exchange platform</description>

    <modules>
        <module>oakpay-parent</module>
        <module>gateway-service</module>
        <module>auth-service</module>
    </modules>
</project>
