import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { authApi } from '../../lib/api';

const LOGO=require('../../assets/Logo_OakPay.png');
const GREEN='#183F2C',LIME='#D8FF3E',TEXT='#111916',MUTED='#6F747B',BG='#F7F8F9',RED='#B42318';

export default function ForgotPasswordScreen(){
 const[email,setEmail]=useState(''); const[error,setError]=useState(''); const[message,setMessage]=useState(''); const[devCode,setDevCode]=useState(''); const[submitting,setSubmitting]=useState(false);
 async function submit(){setError('');setMessage('');setDevCode('');const value=email.trim().toLowerCase();if(!value){setError('Enter your email address.');return;}try{setSubmitting(true);const result=await authApi.forgotPassword(value);setMessage(result.message);if(result.developmentCode){setDevCode(result.developmentCode);}}catch(e){setError(e instanceof Error?e.message:'Unable to request a password reset.');}finally{setSubmitting(false);}}
 return <KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.inner}><Pressable style={styles.back} onPress={()=>router.replace('/(auth)/login')}><Ionicons name="arrow-back" size={20} color={TEXT}/></Pressable><Image source={LOGO} style={styles.logo} resizeMode="contain"/><View style={styles.icon}><Ionicons name="lock-open-outline" size={30} color={GREEN}/></View><Text style={styles.title}>Forgot password?</Text><Text style={styles.description}>Enter your OakPay email and we'll send you a password reset code.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Email address" placeholderTextColor="#70757D" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" returnKeyType="done" onSubmitEditing={submit} style={styles.input}/>{error?<View style={styles.error}><Ionicons name="alert-circle-outline" size={18} color={RED}/><Text style={styles.errorText}>{error}</Text></View>:null}{message?<View style={styles.success}><Ionicons name="checkmark-circle-outline" size={18} color={GREEN}/><Text style={styles.successText}>{message}</Text></View>:null}{devCode?<View style={styles.dev}><Ionicons name="construct-outline" size={17} color={GREEN}/><Text style={styles.devText}>Development reset code: {devCode}</Text></View>:null}<Pressable style={[styles.button,submitting&&styles.disabled]} onPress={submit} disabled={submitting}>{submitting?<ActivityIndicator color="#142019"/>:<Text style={styles.buttonText}>Send reset code</Text>}</Pressable>{message?<Pressable style={styles.resetLink} onPress={()=>router.push({pathname:'/(auth)/reset-password',params:{email}})}><Text style={styles.resetText}>I have a reset code</Text></Pressable>:null}<Pressable onPress={()=>router.replace('/(auth)/login')}><Text style={styles.signIn}>Back to sign in</Text></Pressable></View></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({keyboard:{flex:1,backgroundColor:BG},scroll:{flexGrow:1},inner:{flexGrow:1,paddingHorizontal:32,paddingTop:55,paddingBottom:40,alignItems:'center'},back:{alignSelf:'flex-start',width:42,height:42,borderRadius:13,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E1E4E3',alignItems:'center',justifyContent:'center',marginBottom:24},logo:{width:185,height:62,marginBottom:18},icon:{width:68,height:68,borderRadius:22,backgroundColor:'#E7EEE9',alignItems:'center',justifyContent:'center',marginTop:8,marginBottom:18},title:{fontSize:28,fontWeight:'900',color:TEXT,letterSpacing:-.5},description:{fontSize:14,color:MUTED,marginTop:8,lineHeight:21,textAlign:'center'},input:{width:'100%',height:58,backgroundColor:'#FFF',borderWidth:1,borderColor:'#D8DEDB',borderRadius:16,marginTop:24,paddingHorizontal:16,color:TEXT,fontSize:16},error:{width:'100%',backgroundColor:'#FDECEC',borderRadius:12,padding:11,marginTop:15,flexDirection:'row',alignItems:'center',gap:7},errorText:{flex:1,color:RED,fontSize:12,fontWeight:'700'},success:{width:'100%',backgroundColor:'#E8F3EC',borderRadius:12,padding:11,marginTop:15,flexDirection:'row',alignItems:'center',gap:7},successText:{flex:1,color:GREEN,fontSize:12,fontWeight:'700'},dev:{width:'100%',backgroundColor:'#E8F3EC',borderRadius:12,padding:11,marginTop:10,flexDirection:'row',alignItems:'center',gap:7},devText:{flex:1,color:GREEN,fontSize:12,fontWeight:'800'},button:{width:'100%',height:54,borderRadius:15,backgroundColor:LIME,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.65},buttonText:{fontSize:16,fontWeight:'900',color:'#142019'},resetLink:{paddingVertical:16},resetText:{fontSize:14,fontWeight:'800',color:GREEN},signIn:{fontSize:14,fontWeight:'700',color:MUTED,marginTop:4}});
