import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { authApi } from '../../lib/api';

const LOGO=require('../../assets/Logo_OakPay.png');
const GREEN='#183F2C',LIME='#D8FF3E',TEXT='#111916',MUTED='#6F747B',BG='#F7F8F9',RED='#B42318';

export default function ResetPasswordScreen(){
 const params=useLocalSearchParams<{email?:string}>(); const[email,setEmail]=useState(String(params.email??'')); const[code,setCode]=useState(''); const[password,setPassword]=useState(''); const[confirm,setConfirm]=useState(''); const[error,setError]=useState(''); const[message,setMessage]=useState(''); const[submitting,setSubmitting]=useState(false);
 async function reset(){setError('');setMessage('');const value=email.trim().toLowerCase();if(!value||code.replace(/\D/g,'').length!==6){setError('Enter your email and the 6-digit reset code.');return;}if(password.length<8){setError('Password must be at least 8 characters.');return;}if(password!==confirm){setError('Passwords do not match.');return;}try{setSubmitting(true);const result=await authApi.resetPassword(value,code.replace(/\D/g,''),password);if(result.reset){setMessage(result.message);setTimeout(()=>router.replace('/(auth)/login'),900);}}catch(e){setError(e instanceof Error?e.message:'Unable to reset your password.');}finally{setSubmitting(false);}}
 return <KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.inner}><Pressable style={styles.back} onPress={()=>router.replace('/(auth)/login')}><Ionicons name="arrow-back" size={20} color={TEXT}/></Pressable><Image source={LOGO} style={styles.logo} resizeMode="contain"/><View style={styles.icon}><Ionicons name="key-outline" size={30} color={GREEN}/></View><Text style={styles.title}>Reset password</Text><Text style={styles.description}>Enter the code we sent to your email and choose a new password.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Email address" placeholderTextColor="#70757D" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" style={styles.input}/><TextInput value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} placeholder="6-digit code" placeholderTextColor="#70757D" keyboardType="number-pad" maxLength={6} style={styles.input}/><TextInput value={password} onChangeText={setPassword} placeholder="New password" placeholderTextColor="#70757D" secureTextEntry style={styles.input}/><TextInput value={confirm} onChangeText={setConfirm} placeholder="Confirm new password" placeholderTextColor="#70757D" secureTextEntry returnKeyType="done" onSubmitEditing={reset} style={styles.input}/>{error?<View style={styles.error}><Ionicons name="alert-circle-outline" size={18} color={RED}/><Text style={styles.errorText}>{error}</Text></View>:null}{message?<View style={styles.success}><Ionicons name="checkmark-circle-outline" size={18} color={GREEN}/><Text style={styles.successText}>{message}</Text></View>:null}<Pressable style={[styles.button,submitting&&styles.disabled]} onPress={reset} disabled={submitting}>{submitting?<ActivityIndicator color="#142019"/>:<Text style={styles.buttonText}>Reset password</Text>}</Pressable><Pressable onPress={()=>router.replace({pathname:'/(auth)/forgot-password',params:{email}})}><Text style={styles.link}>Request a new code</Text></Pressable></View></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({keyboard:{flex:1,backgroundColor:BG},scroll:{flexGrow:1},inner:{flexGrow:1,paddingHorizontal:32,paddingTop:55,paddingBottom:40,alignItems:'center'},back:{alignSelf:'flex-start',width:42,height:42,borderRadius:13,backgroundColor:'#FFF',borderWidth:1,borderColor:'#E1E4E3',alignItems:'center',justifyContent:'center',marginBottom:24},logo:{width:185,height:62,marginBottom:18},icon:{width:68,height:68,borderRadius:22,backgroundColor:'#E7EEE9',alignItems:'center',justifyContent:'center',marginTop:8,marginBottom:18},title:{fontSize:28,fontWeight:'900',color:TEXT},description:{fontSize:14,color:MUTED,marginTop:8,lineHeight:21,textAlign:'center'},input:{width:'100%',height:56,backgroundColor:'#FFF',borderWidth:1,borderColor:'#D8DEDB',borderRadius:16,marginTop:13,paddingHorizontal:16,color:TEXT,fontSize:16},error:{width:'100%',backgroundColor:'#FDECEC',borderRadius:12,padding:11,marginTop:15,flexDirection:'row',alignItems:'center',gap:7},errorText:{flex:1,color:RED,fontSize:12,fontWeight:'700'},success:{width:'100%',backgroundColor:'#E8F3EC',borderRadius:12,padding:11,marginTop:15,flexDirection:'row',alignItems:'center',gap:7},successText:{flex:1,color:GREEN,fontSize:12,fontWeight:'700'},button:{width:'100%',height:54,borderRadius:15,backgroundColor:LIME,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.65},buttonText:{fontSize:16,fontWeight:'900',color:'#142019'},link:{fontSize:14,fontWeight:'800',color:GREEN,paddingVertical:16}});
