import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { authApi } from '../../lib/api';

const LOGO=require('../../assets/Logo_OakPay.png');
const GREEN='#183F2C',LIME='#D8FF3E',TEXT='#111916',MUTED='#6F747B',BG='#F7F8F9',RED='#B42318';

export default function VerifyEmailScreen(){
 const params=useLocalSearchParams<{email?:string}>(); const email=String(params.email??'');
 const[code,setCode]=useState(''); const[error,setError]=useState(''); const[message,setMessage]=useState(''); const[submitting,setSubmitting]=useState(false); const[resending,setResending]=useState(false); const[countdown,setCountdown]=useState(0);
 useEffect(()=>{if(countdown<=0)return;const timer=setInterval(()=>setCountdown(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer);},[countdown]);
 async function verify(){setError('');setMessage('');const value=code.replace(/\D/g,'');if(value.length!==6){setError('Enter the 6-digit verification code.');return;}if(!email){setError('Your registration email is missing. Please register again.');return;}try{setSubmitting(true);const result=await authApi.verifyEmail(email,value);if(result.verified){setMessage('Email verified successfully.');setTimeout(()=>router.replace('/(auth)/login'),700);}}catch(e){setError(e instanceof Error?e.message:'Unable to verify your email.');}finally{setSubmitting(false);}}
 async function resend(){setError('');setMessage('');if(!email){setError('Your registration email is missing. Please register again.');return;}try{setResending(true);const result=await authApi.resendVerification(email);setMessage(result.message);setCountdown(60);}catch(e){setError(e instanceof Error?e.message:'Unable to resend the verification code.');}finally{setResending(false);}}
 return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.inner}><Pressable style={styles.back} onPress={()=>router.replace('/(auth)/login')}><Ionicons name="arrow-back" size={20} color={TEXT}/></Pressable><Image source={LOGO} style={styles.logo} resizeMode="contain"/><View style={styles.icon}><Ionicons name="mail-outline" size={30} color={GREEN}/></View><Text style={styles.title}>Verify your email</Text><Text style={styles.description}>We sent a 6-digit verification code to</Text><Text style={styles.email}>{email||'your email address'}</Text><TextInput value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} placeholder="000000" placeholderTextColor="#A4AAA7" style={styles.codeInput} textContentType="oneTimeCode" autoComplete="one-time-code"/><Text style={styles.helper}>The code expires in 15 minutes.</Text>{error?<View style={styles.error}><Ionicons name="alert-circle-outline" size={18} color={RED}/><Text style={styles.errorText}>{error}</Text></View>:null}{message?<View style={styles.success}><Ionicons name="checkmark-circle-outline" size={18} color={GREEN}/><Text style={styles.successText}>{message}</Text></View>:null}<Pressable style={[styles.button,submitting&&styles.disabled]} onPress={verify} disabled={submitting}>{submitting?<ActivityIndicator color="#142019"/>:<Text style={styles.buttonText}>Verify email</Text>}</Pressable><Pressable onPress={resend} disabled={resending||countdown>0} style={styles.resend}><Text style={[styles.resendText,(resending||countdown>0)&&styles.resendDisabled]}>{resending?'Sending…':countdown>0?`Resend code in ${countdown}s`:'Resend verification code'}</Text></Pressable><Pressable onPress={()=>router.replace('/(auth)/login')}><Text style={styles.signIn}>Back to sign in</Text></Pressable></View></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:BG},inner:{flex:1,paddingHorizontal:32,paddingTop:55,alignItems:'center'},back:{alignSelf:'flex-start',width:42,height:42,borderRadius:13,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#E1E4E3',alignItems:'center',justifyContent:'center',marginBottom:24},logo:{width:185,height:62,marginBottom:18},icon:{width:68,height:68,borderRadius:22,backgroundColor:'#E7EEE9',alignItems:'center',justifyContent:'center',marginTop:8,marginBottom:18},title:{fontSize:28,fontWeight:'900',color:TEXT,letterSpacing:-.5},description:{fontSize:14,color:MUTED,marginTop:8},email:{fontSize:14,fontWeight:'800',color:TEXT,marginTop:4,maxWidth:'100%'},codeInput:{width:'100%',height:64,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#D8DEDB',borderRadius:16,marginTop:25,textAlign:'center',fontSize:28,fontWeight:'900',letterSpacing:8,color:TEXT},helper:{fontSize:11,color:MUTED,marginTop:8},error:{width:'100%',backgroundColor:'#FDECEC',borderRadius:12,padding:11,marginTop:15,flexDirection:'row',alignItems:'center',gap:7},errorText:{flex:1,color:RED,fontSize:12,fontWeight:'700'},success:{width:'100%',backgroundColor:'#E8F3EC',borderRadius:12,padding:11,marginTop:15,flexDirection:'row',alignItems:'center',gap:7},successText:{flex:1,color:GREEN,fontSize:12,fontWeight:'700'},button:{width:'100%',height:54,borderRadius:15,backgroundColor:LIME,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.65},buttonText:{fontSize:16,fontWeight:'900',color:'#142019'},resend:{paddingVertical:16},resendText:{fontSize:14,fontWeight:'800',color:GREEN},resendDisabled:{color:'#9BA29F'},signIn:{fontSize:14,fontWeight:'700',color:MUTED,marginTop:4}});
