spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes: []

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
