import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useFocusEffect } from '@react-navigation/native';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../../context/AuthContext';
import { isAuthError } from '../../lib/api';
import { KycProfile, kycApi } from '../../lib/kycApi';

const BG='#0D1017',CARD='#171B24',TEXT='#F4F6F8',MUTED='#8D95A3',LIME='#D8FF3E',BORDER='#242A34';
const label=(s:string)=>s.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const statusColor=(s:string)=>s==='VERIFIED'?LIME:s==='REJECTED'?'#FF8F8F':s==='PENDING'?'#E2B84B':MUTED;
export default function KycScreen(){
 const {accessToken,refreshSession}=useAuth(); const [kyc,setKyc]=useState<KycProfile|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=useCallback(async()=>{if(!accessToken){setLoading(false);return;}setLoading(true);setError('');try{setKyc(await kycApi.get(accessToken));}catch(e){if(isAuthError(e)){const ok=await refreshSession();if(!ok)setError('Your session has expired. Please sign in again.');}else setError(e instanceof Error?e.message:'Unable to load KYC status.');}finally{setLoading(false);}},[accessToken,refreshSession]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 const status=kyc?.status??'NOT_STARTED'; const canStart=status==='NOT_STARTED'||status==='REJECTED';
 return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content}><View style={styles.container}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color={TEXT}/></Pressable><Text style={styles.title}>KYC verification</Text><View style={styles.spacer}/></View>
  <View style={styles.statusCard}><View style={styles.statusIcon}><Ionicons name={status==='VERIFIED'?'checkmark-circle-outline':status==='PENDING'?'time-outline':'shield-checkmark-outline'} size={28} color={statusColor(status)}/></View>{loading?<ActivityIndicator color={LIME}/>:<><Text style={[styles.status,{color:statusColor(status)}]}>{label(status)}</Text><Text style={styles.statusText}>{status==='VERIFIED'?'Your identity has been verified.':status==='PENDING'?'Your identity documents are under review.':status==='REJECTED'?(kyc?.rejectionReason||'Your KYC submission was rejected. Review the requirements and resubmit.'):'Complete identity verification to unlock features that require a verified OakPay account.'}</Text></>}</View>
  <View style={styles.card}><Text style={styles.section}>Verification steps</Text>{[['person-outline','Personal information','Confirm your basic identity details'],['document-text-outline','Identity document','Submit a supported government-issued document'],['time-outline','Review','OakPay reviews your submission']].map(([icon,title,text])=><View style={styles.step} key={title}><View style={styles.stepIcon}><Ionicons name={icon as any} size={19} color={LIME}/></View><View style={styles.copy}><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepText}>{text}</Text></View></View>)}</View>
  {error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable onPress={load}><Text style={styles.retry}>Retry</Text></Pressable></View>:null}
  {canStart?<Pressable style={styles.primary} onPress={()=>router.push('/(tabs)/identity-documents')}><Text style={styles.primaryText}>{status==='REJECTED'?'Review and resubmit':'Start verification'}</Text></Pressable>:null}
  {status==='PENDING'?<View style={styles.info}><Ionicons name="information-circle-outline" size={18} color="#E2B84B"/><Text style={styles.infoText}>No action is required while your submission is under review.</Text></View>:null}
  <Text style={styles.note}>KYC approval is completed through OakPay's review process.</Text></View></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},content:{paddingBottom:40},container:{paddingHorizontal:20,paddingTop:8},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},back:{width:42,height:42,borderRadius:14,backgroundColor:CARD,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center'},spacer:{width:42},title:{color:TEXT,fontFamily:'Inter_800ExtraBold',fontSize:25},statusCard:{backgroundColor:CARD,borderRadius:22,borderWidth:1,borderColor:BORDER,padding:22,alignItems:'center'},statusIcon:{width:62,height:62,borderRadius:20,backgroundColor:'#242A17',alignItems:'center',justifyContent:'center',marginBottom:12},status:{fontFamily:'Inter_800ExtraBold',fontSize:18},statusText:{color:MUTED,fontFamily:'Inter_400Regular',fontSize:12,lineHeight:18,textAlign:'center',marginTop:7},card:{backgroundColor:CARD,borderRadius:20,borderWidth:1,borderColor:BORDER,padding:16,marginTop:16},section:{color:TEXT,fontFamily:'Inter_800ExtraBold',fontSize:16,marginBottom:7},step:{flexDirection:'row',alignItems:'center',paddingVertical:13},stepIcon:{width:40,height:40,borderRadius:13,backgroundColor:'#242A17',alignItems:'center',justifyContent:'center'},copy:{flex:1,marginLeft:12},stepTitle:{color:TEXT,fontFamily:'Inter_700Bold',fontSize:13},stepText:{color:MUTED,fontFamily:'Inter_400Regular',fontSize:11,lineHeight:16,marginTop:2},primary:{height:52,borderRadius:15,backgroundColor:LIME,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:'#10151D',fontFamily:'Inter_800ExtraBold',fontSize:14},error:{marginTop:14,padding:12,borderRadius:12,backgroundColor:'#21171B',borderWidth:1,borderColor:'#42272A',flexDirection:'row',justifyContent:'space-between'},errorText:{color:'#FFB6B6',fontFamily:'Inter_400Regular',fontSize:11,flex:1},retry:{color:LIME,fontFamily:'Inter_800ExtraBold',fontSize:11},info:{marginTop:14,padding:12,borderRadius:12,backgroundColor:'#2D2A20',flexDirection:'row',gap:8,alignItems:'center'},infoText:{color:'#E2B84B',fontFamily:'Inter_400Regular',fontSize:11,flex:1},note:{color:MUTED,fontFamily:'Inter_400Regular',fontSize:10,lineHeight:15,textAlign:'center',marginTop:10}});
