import { Ionicons } from '@expo/vector-icons';
import DateTimePicker from '@expo/ui/community/datetime-picker';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../../context/AuthContext';
import { UserResponse } from '../../lib/api';
import { accountApi } from '../../lib/accountApi';

const BG='#0D1017',CARD='#171B24',TEXT='#F4F6F8',MUTED='#8D95A3',LIME='#D8FF3E',BORDER='#242A34';

type FieldProps={label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;keyboardType?:'default'|'phone-pad'};
function Field({label,value,onChangeText,placeholder,keyboardType='default'}:FieldProps){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={MUTED} keyboardType={keyboardType} returnKeyType="next" style={styles.input}/></View>}

function parseDate(value:string){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)return new Date(2000,0,1);const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]));return Number.isNaN(date.getTime())?new Date(2000,0,1):date}
function formatDate(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}

export default function PersonalDetailsScreen(){
 const {user,accessToken}=useAuth();
 const [profile,setProfile]=useState<UserResponse|null>(user);
 const [firstName,setFirstName]=useState(user?.firstName??''); const [lastName,setLastName]=useState(user?.lastName??''); const [phoneNumber,setPhoneNumber]=useState(user?.phoneNumber??''); const [country,setCountry]=useState(user?.country??''); const [dateOfBirth,setDateOfBirth]=useState(user?.dateOfBirth??'');
 const [showDatePicker,setShowDatePicker]=useState(false); const [saving,setSaving]=useState(false);
 async function save(){if(!accessToken)return;if(!firstName.trim()||!lastName.trim()){Alert.alert('Missing information','First name and last name are required.');return;}setSaving(true);try{const updated=await accountApi.updateProfile(accessToken,{firstName:firstName.trim(),lastName:lastName.trim(),phoneNumber:phoneNumber.trim(),country:country.trim(),dateOfBirth:dateOfBirth.trim()||null});setProfile(updated);Alert.alert('Profile updated','Your personal details have been saved.',[{text:'OK',onPress:()=>router.back()}]);}catch(e){Alert.alert('Update failed',e instanceof Error?e.message:'We could not update your profile.');}finally{setSaving(false);}}
 return <SafeAreaView style={styles.safe} edges={['top']}><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS==='ios'?'padding':'height'} keyboardVerticalOffset={Platform.OS==='ios'?8:0}><ScrollView keyboardShouldPersistTaps="always" keyboardDismissMode="none" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.container}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color={TEXT}/></Pressable><Text style={styles.title}>Personal details</Text><View style={styles.spacer}/></View><Text style={styles.subtitle}>Keep your OakPay account information up to date.</Text><View style={styles.card}><Field label="FIRST NAME" value={firstName} onChangeText={setFirstName} placeholder="First name"/><Field label="LAST NAME" value={lastName} onChangeText={setLastName} placeholder="Last name"/><Field label="PHONE NUMBER" value={phoneNumber} onChangeText={setPhoneNumber} placeholder="Phone number" keyboardType="phone-pad"/><Field label="COUNTRY" value={country} onChangeText={setCountry} placeholder="Country"/>
 <View style={styles.field}><Text style={styles.label}>DATE OF BIRTH</Text><Pressable style={styles.inputButton} onPress={()=>setShowDatePicker(true)}><Text style={[styles.inputButtonText,!dateOfBirth&&styles.placeholder]}>{dateOfBirth||'Select date of birth'}</Text><Ionicons name="calendar-outline" size={18} color={LIME}/></Pressable></View>
 {showDatePicker&&<DateTimePicker value={parseDate(dateOfBirth)} mode="date" presentation="dialog" maximumDate={new Date()} onValueChange={(_,date)=>{setDateOfBirth(formatDate(date));setShowDatePicker(false)}} onDismiss={()=>setShowDatePicker(false)} accentColor={LIME}/>} 
 <Text style={styles.label}>EMAIL</Text><View style={styles.readonly}><Text style={styles.readonlyText}>{profile?.email??user?.email??'No email available'}</Text><Ionicons name="lock-closed-outline" size={15} color={MUTED}/></View><Text style={styles.hint}>Email changes require a separate verification process.</Text></View><Pressable disabled={saving} style={[styles.save,saving&&styles.disabled]} onPress={save}><Text style={styles.saveText}>{saving?'Saving…':'Save changes'}</Text></Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},keyboard:{flex:1},content:{paddingBottom:50},container:{paddingHorizontal:20,paddingTop:8},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},back:{width:42,height:42,borderRadius:14,backgroundColor:CARD,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center'},spacer:{width:42},title:{color:TEXT,fontSize:25,fontWeight:'800'},subtitle:{color:MUTED,fontSize:12,lineHeight:18,marginBottom:18},card:{backgroundColor:CARD,borderRadius:20,borderWidth:1,borderColor:BORDER,padding:16},field:{marginBottom:15},label:{color:MUTED,fontSize:9,fontWeight:'800',letterSpacing:1,marginBottom:7},input:{height:48,borderRadius:13,borderWidth:1,borderColor:BORDER,backgroundColor:'#10151D',paddingHorizontal:13,color:TEXT,fontSize:14},inputButton:{height:48,borderRadius:13,borderWidth:1,borderColor:BORDER,backgroundColor:'#10151D',paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},inputButtonText:{color:TEXT,fontSize:14},placeholder:{color:MUTED},readonly:{height:48,borderRadius:13,borderWidth:1,borderColor:BORDER,backgroundColor:'#10151D',paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},readonlyText:{color:MUTED,fontSize:14},hint:{color:MUTED,fontSize:10,lineHeight:15,marginTop:7},save:{height:52,borderRadius:15,backgroundColor:LIME,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.5},saveText:{color:'#10151D',fontWeight:'800',fontSize:14}});
