import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../../context/AuthContext';
import { accountApi } from '../../lib/accountApi';
const BG='#0D1017',CARD='#171B24',TEXT='#F4F6F8',MUTED='#8D95A3',LIME='#D8FF3E',BORDER='#242A34';
export default function SecurityScreen(){
 const {accessToken}=useAuth(); const [showChange,setShowChange]=useState(false); const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirm,setConfirm]=useState(''); const [saving,setSaving]=useState(false);
 const changePassword=async()=>{if(!accessToken)return;if(!current||!next||!confirm)return Alert.alert('Missing information','Complete all password fields.');if(next.length<8)return Alert.alert('Password too short','Your new password must be at least 8 characters.');if(next!==confirm)return Alert.alert('Passwords do not match','Confirm your new password correctly.');setSaving(true);try{await accountApi.changePassword(accessToken,current,next);setCurrent('');setNext('');setConfirm('');setShowChange(false);Alert.alert('Password changed','Your OakPay password has been updated successfully.');}catch(e){Alert.alert('Unable to change password',e instanceof Error?e.message:'We could not change your password.');}finally{setSaving(false);}};
 return <SafeAreaView style={styles.safe} edges={['top']}><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.container}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color={TEXT}/></Pressable><Text style={styles.title}>Security</Text><View style={styles.spacer}/></View>
 <View style={styles.card}><View style={styles.row}><View style={styles.icon}><Ionicons name="mail-outline" size={20} color={LIME}/></View><View style={styles.copy}><Text style={styles.rowTitle}>Email verification</Text><Text style={styles.rowText}>Your email is verified and linked to this account.</Text></View><Ionicons name="checkmark-circle" size={20} color={LIME}/></View><View style={styles.divider}/>
 <Pressable style={styles.row} onPress={()=>setShowChange(v=>!v)}><View style={styles.icon}><Ionicons name="key-outline" size={20} color={LIME}/></View><View style={styles.copy}><Text style={styles.rowTitle}>Change password</Text><Text style={styles.rowText}>Update your OakPay password.</Text></View><Ionicons name={showChange?'chevron-down':'chevron-forward'} size={20} color={MUTED}/></Pressable>
 {showChange&&<View style={styles.passwordBox}><TextInput value={current} onChangeText={setCurrent} placeholder="Current password" placeholderTextColor={MUTED} secureTextEntry style={styles.input}/><TextInput value={next} onChangeText={setNext} placeholder="New password" placeholderTextColor={MUTED} secureTextEntry style={styles.input}/><TextInput value={confirm} onChangeText={setConfirm} placeholder="Confirm new password" placeholderTextColor={MUTED} secureTextEntry style={styles.input}/><Pressable disabled={saving} style={[styles.changeButton,saving&&styles.disabled]} onPress={changePassword}><Text style={styles.changeText}>{saving?'Updating…':'Update password'}</Text></Pressable></View>}
 <View style={styles.divider}/><View style={styles.row}><View style={styles.icon}><Ionicons name="phone-portrait-outline" size={20} color={MUTED}/></View><View style={styles.copy}><Text style={styles.rowTitle}>Two-factor authentication</Text><Text style={styles.rowText}>Additional account protection will be available in a later security release.</Text></View><Text style={styles.badge}>SOON</Text></View></View>
 <View style={styles.info}><Ionicons name="shield-checkmark-outline" size={18} color={LIME}/><Text style={styles.infoText}>Never share your password, verification codes or recovery codes with anyone.</Text></View></View></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},keyboard:{flex:1},content:{paddingBottom:40},container:{paddingHorizontal:20,paddingTop:8},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},back:{width:42,height:42,borderRadius:14,backgroundColor:CARD,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center'},spacer:{width:42},title:{color:TEXT,fontSize:25,fontWeight:'800'},card:{backgroundColor:CARD,borderRadius:20,borderWidth:1,borderColor:BORDER,paddingHorizontal:16},row:{minHeight:76,flexDirection:'row',alignItems:'center'},icon:{width:40,height:40,borderRadius:13,backgroundColor:'#242A17',alignItems:'center',justifyContent:'center'},copy:{flex:1,marginHorizontal:12},rowTitle:{color:TEXT,fontSize:13,fontWeight:'700'},rowText:{color:MUTED,fontSize:11,lineHeight:16,marginTop:3},divider:{height:1,backgroundColor:BORDER,marginLeft:52},badge:{color:MUTED,fontSize:9,fontWeight:'800',letterSpacing:1},passwordBox:{paddingBottom:15},input:{height:48,borderRadius:13,borderWidth:1,borderColor:BORDER,backgroundColor:'#10151D',paddingHorizontal:13,color:TEXT,fontSize:14,marginBottom:9},changeButton:{height:48,borderRadius:13,backgroundColor:LIME,alignItems:'center',justifyContent:'center'},changeText:{color:'#10151D',fontSize:13,fontWeight:'800'},disabled:{opacity:.5},info:{marginTop:16,borderRadius:16,borderWidth:1,borderColor:BORDER,backgroundColor:CARD,padding:14,flexDirection:'row',alignItems:'flex-start',gap:9},infoText:{flex:1,color:MUTED,fontSize:10,lineHeight:15}});
