import { Ionicons } from '@expo/vector-icons';
import QRCode from 'react-native-qrcode-svg';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../../context/AuthContext';
import { twoFactorApi } from '../../lib/twoFactorApi';

const BG='#0D1017',CARD='#171B24',TEXT='#F4F6F8',MUTED='#8D95A3',LIME='#D8FF3E',BORDER='#242A34';

export default function SecurityScreen(){
 const {accessToken}=useAuth();
 const [twoFactorEnabled,setTwoFactorEnabled]=useState(false); const [setup,setSetup]=useState<{secret:string;otpauthUri:string}|null>(null); const [setupCode,setSetupCode]=useState(''); const [disablePassword,setDisablePassword]=useState(''); const [disableCode,setDisableCode]=useState(''); const [showDisable,setShowDisable]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 useEffect(()=>{let active=true;(async()=>{if(!accessToken)return;try{const status=await twoFactorApi.status(accessToken);if(active)setTwoFactorEnabled(status.enabled);}catch{}finally{if(active)setLoading(false);}})();return()=>{active=false;}},[accessToken]);
 const startSetup=async()=>{if(!accessToken)return;try{setSaving(true);const data=await twoFactorApi.setup(accessToken);setSetup(data);setSetupCode('');}catch(e){Alert.alert('Unable to start 2FA',e instanceof Error?e.message:'Please try again.');}finally{setSaving(false);}};
 const enable=async()=>{if(!accessToken)return;if(!/^\d{6}$/.test(setupCode))return Alert.alert('Invalid code','Enter the 6-digit code from your authenticator app.');try{setSaving(true);await twoFactorApi.enable(accessToken,setupCode);setTwoFactorEnabled(true);setSetup(null);setSetupCode('');Alert.alert('2FA enabled','Two-factor authentication is now protecting your OakPay account.');}catch(e){Alert.alert('Unable to enable 2FA',e instanceof Error?e.message:'Invalid authenticator code.');}finally{setSaving(false);}};
 const disable=async()=>{if(!accessToken)return;if(!disablePassword||!/^\d{6}$/.test(disableCode))return Alert.alert('Missing information','Enter your password and the 6-digit authenticator code.');try{setSaving(true);await twoFactorApi.disable(accessToken,disablePassword,disableCode);setTwoFactorEnabled(false);setShowDisable(false);setDisablePassword('');setDisableCode('');Alert.alert('2FA disabled','Two-factor authentication has been disabled.');}catch(e){Alert.alert('Unable to disable 2FA',e instanceof Error?e.message:'Please check your password and authenticator code.');}finally{setSaving(false);}};
 return <SafeAreaView style={styles.safe} edges={['top']}><KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.container}><View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color={TEXT}/></Pressable><Text style={styles.title}>Security</Text><View style={styles.spacer}/></View>
 <View style={styles.card}><View style={styles.row}><View style={styles.icon}><Ionicons name="mail-outline" size={20} color={LIME}/></View><View style={styles.copy}><Text style={styles.rowTitle}>Email verification</Text><Text style={styles.rowText}>Your email is verified and linked to this account.</Text></View><Ionicons name="checkmark-circle" size={20} color={LIME}/></View><View style={styles.divider}/>
 <View style={styles.row}><View style={styles.icon}><Ionicons name="key-outline" size={20} color={LIME}/></View><View style={styles.copy}><Text style={styles.rowTitle}>Change password</Text><Text style={styles.rowText}>Update your OakPay password.</Text></View><Pressable onPress={()=>router.push('/(tabs)/security')}><Ionicons name="chevron-forward" size={20} color={MUTED}/></Pressable></View><View style={styles.divider}/>
 <View style={styles.row}><View style={styles.icon}><Ionicons name="phone-portrait-outline" size={20} color={LIME}/></View><View style={styles.copy}><Text style={styles.rowTitle}>Two-factor authentication</Text><Text style={styles.rowText}>{loading?'Checking security status…':twoFactorEnabled?'Authenticator app protection is enabled.':'Protect your account with an authenticator app.'}</Text></View>{!loading?<View style={[styles.statusDot,twoFactorEnabled&&styles.statusDotOn]}/>:null}</View>
 {!loading&&!twoFactorEnabled&&!setup?<Pressable style={styles.primaryButton} disabled={saving} onPress={startSetup}><Text style={styles.primaryText}>{saving?'Starting…':'Set up authenticator'}</Text></Pressable>:null}
 {setup?<View style={styles.setupBox}><Text style={styles.setupTitle}>1. Scan this QR code</Text><View style={styles.qr}><QRCode value={setup.otpauthUri} size={180} backgroundColor="#FFFFFF" color="#111916"/></View><Text style={styles.setupHint}>If your authenticator cannot scan it, enter this setup key manually:</Text><Text selectable style={styles.secret}>{setup.secret}</Text><Text style={styles.setupTitle}>2. Enter the 6-digit code</Text><TextInput value={setupCode} onChangeText={v=>setSetupCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" textContentType="oneTimeCode" maxLength={6} placeholder="000000" placeholderTextColor={MUTED} style={styles.codeInput}/><Pressable style={[styles.primaryButton,saving&&styles.disabled]} disabled={saving} onPress={enable}><Text style={styles.primaryText}>{saving?'Enabling…':'Enable 2FA'}</Text></Pressable><Pressable onPress={()=>setSetup(null)}><Text style={styles.cancel}>Cancel setup</Text></Pressable></View>:null}
 {twoFactorEnabled&&!setup?<><Pressable style={styles.secondaryButton} onPress={()=>setShowDisable(v=>!v)}><Text style={styles.secondaryText}>{showDisable?'Cancel':'Disable 2FA'}</Text></Pressable>{showDisable?<View style={styles.disableBox}><TextInput value={disablePassword} onChangeText={setDisablePassword} secureTextEntry placeholder="Current password" placeholderTextColor={MUTED} style={styles.input}/><TextInput value={disableCode} onChangeText={v=>setDisableCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} placeholder="Authenticator code" placeholderTextColor={MUTED} style={styles.input}/><Pressable style={[styles.dangerButton,saving&&styles.disabled]} disabled={saving} onPress={disable}><Text style={styles.dangerText}>{saving?'Disabling…':'Disable two-factor authentication'}</Text></Pressable></View>:null}</>:null}
 </View><View style={styles.info}><Ionicons name="shield-checkmark-outline" size={18} color={LIME}/><Text style={styles.infoText}>Never share your password, authenticator codes or recovery information with anyone.</Text></View></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},keyboard:{flex:1},content:{paddingBottom:40},container:{paddingHorizontal:20,paddingTop:8},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},back:{width:42,height:42,borderRadius:14,backgroundColor:CARD,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center'},spacer:{width:42},title:{color:TEXT,fontSize:25,fontWeight:'800'},card:{backgroundColor:CARD,borderRadius:20,borderWidth:1,borderColor:BORDER,paddingHorizontal:16,paddingBottom:16},row:{minHeight:76,flexDirection:'row',alignItems:'center'},icon:{width:40,height:40,borderRadius:13,backgroundColor:'#242A17',alignItems:'center',justifyContent:'center'},copy:{flex:1,marginHorizontal:12},rowTitle:{color:TEXT,fontSize:13,fontWeight:'700'},rowText:{color:MUTED,fontSize:11,lineHeight:16,marginTop:3},divider:{height:1,backgroundColor:BORDER,marginLeft:52},statusDot:{width:9,height:9,borderRadius:5,backgroundColor:MUTED},statusDotOn:{backgroundColor:LIME},primaryButton:{height:48,borderRadius:14,backgroundColor:LIME,alignItems:'center',justifyContent:'center',marginTop:10},primaryText:{color:'#10151D',fontSize:13,fontWeight:'800'},secondaryButton:{height:46,borderRadius:14,borderWidth:1,borderColor:BORDER,alignItems:'center',justifyContent:'center',marginTop:10},secondaryText:{color:TEXT,fontSize:13,fontWeight:'700'},setupBox:{borderTopWidth:1,borderTopColor:BORDER,marginTop:12,paddingTop:18},setupTitle:{color:TEXT,fontSize:13,fontWeight:'800',marginBottom:12},qr:{backgroundColor:'#FFFFFF',alignSelf:'center',padding:12,borderRadius:14,marginBottom:14},setupHint:{color:MUTED,fontSize:11,lineHeight:16,textAlign:'center'},secret:{color:LIME,fontSize:13,fontWeight:'800',letterSpacing:1.5,textAlign:'center',marginVertical:12},codeInput:{height:52,borderRadius:14,borderWidth:1,borderColor:BORDER,backgroundColor:'#10151D',color:TEXT,textAlign:'center',fontSize:20,fontWeight:'800',letterSpacing:7},cancel:{color:MUTED,textAlign:'center',fontSize:12,fontWeight:'700',marginTop:14},disableBox:{paddingTop:12},input:{height:48,borderRadius:13,borderWidth:1,borderColor:BORDER,backgroundColor:'#10151D',paddingHorizontal:13,color:TEXT,fontSize:14,marginBottom:9},dangerButton:{height:48,borderRadius:13,borderWidth:1,borderColor:'#7A2F35',alignItems:'center',justifyContent:'center'},dangerText:{color:'#FFB4AB',fontSize:12,fontWeight:'800'},disabled:{opacity:.5},info:{marginTop:16,borderRadius:16,borderWidth:1,borderColor:BORDER,backgroundColor:CARD,padding:14,flexDirection:'row',alignItems:'flex-start',gap:9},infoText:{flex:1,color:MUTED,fontSize:10,lineHeight:15}});
